CREATE TABLE `creaturecache` (
  `Entry` mediumint(8) unsigned NOT NULL default '0',
  `Name` varchar(255) NOT NULL,
  `Name2` varchar(255) NOT NULL,
  `Name3` varchar(255) NOT NULL,
  `Name4` varchar(255) NOT NULL,
  `SubName` varchar(255) NOT NULL,
  `IconName` varchar(255) NOT NULL,
  `TypeFlags` int(10) unsigned NOT NULL default '0',
  `Type` int(10) unsigned NOT NULL default '0',
  `Family` int(10) unsigned NOT NULL default '0',
  `Rank` int(10) unsigned NOT NULL default '0',
  `KillCredid1` int(10) unsigned NOT NULL default '0',
  `KillCredit2` int(10) unsigned NOT NULL default '0',
  `DisplayID1` int(10) unsigned NOT NULL default '0',
  `DisplayID2` int(10) unsigned NOT NULL default '0',
  `DisplayID3` int(10) unsigned NOT NULL default '0',
  `DisplayID4` int(10) unsigned NOT NULL default '0',
  `HealthModifier` float NOT NULL default '0',
  `ManaModifier` float NOT NULL default '0',
  `RacialLeader` int(10) unsigned NOT NULL default '0',
  `QuestItem1` int(10) unsigned NOT NULL default '0',
  `QuestItem2` int(10) unsigned NOT NULL default '0',
  `QuestItem3` int(10) unsigned NOT NULL default '0',
  `QuestItem4` int(10) unsigned NOT NULL default '0',
  `QuestItem5` int(10) unsigned NOT NULL default '0',
  `QuestItem6` int(10) unsigned NOT NULL default '0',
  `MovementID` int(10) unsigned NOT NULL default '0',
  `Unk` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`Entry`),
  KEY `idx_name` (`Name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
