CREATE TABLE `questcache` (
  `Entry` mediumint(8) unsigned NOT NULL default '0',
  `Method` mediumint(8) unsigned NOT NULL default '0',
  `QuestLevel` mediumint(8) NOT NULL default '0',
  `MinLevel` mediumint(8) unsigned NOT NULL default '0',
  `ZoneOrSort` mediumint(8) NOT NULL default '0',
  `Type` mediumint(8) unsigned NOT NULL default '0',
  `SuggestedPlayers` mediumint(8) unsigned NOT NULL default '0',
  `RepObjFaction` mediumint(8) unsigned NOT NULL default '0',
  `RepObjValue` mediumint(8) NOT NULL default '0',
  `RepObjFaction1` mediumint(8) unsigned NOT NULL default '0',
  `RepObjValue1` mediumint(8) NOT NULL default '0',
  `NextQuest` mediumint(8) unsigned NOT NULL default '0',
  `XPID` mediumint(8) unsigned NOT NULL default '0',
  `RewOrReqMoney` mediumint(8) NOT NULL default '0',
  `RewMoneyMaxLevel` mediumint(8) unsigned NOT NULL default '0',
  `RewSpell` mediumint(8) unsigned NOT NULL default '0',
  `RewSpellCast` mediumint(8) unsigned NOT NULL default '0',
  `Honor1` mediumint(8) unsigned NOT NULL default '0',
  `Honor2` float NOT NULL default '0',
  `SrcItemID` mediumint(8) unsigned NOT NULL default '0',
  `QuestFlags` mediumint(8) unsigned NOT NULL default '0',
  `QuestFlags2` mediumint(8) unsigned NOT NULL default '0',
  `RewTitle` mediumint(8) unsigned NOT NULL default '0',
  `ReqPlayersSlain` mediumint(8) unsigned NOT NULL default '0',
  `BonusTalents` mediumint(8) unsigned NOT NULL default '0',
  `BonusArenaPoints` mediumint(8) unsigned NOT NULL default '0',
  `RewardSkillLineID` mediumint(8) unsigned NOT NULL default '0',
  `RewardSkillPoints` mediumint(8) unsigned NOT NULL default '0',
  `RewardFactionMask` mediumint(8) unsigned NOT NULL default '0',
  `QuestGiverPortraitID` mediumint(8) unsigned NOT NULL default '0',
  `QuestTurnInPortraitID` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId1` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId2` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId3` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId4` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId1` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId2` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId3` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId5` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount5` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemId6` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiceItemCount6` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId1` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId2` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId3` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId4` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId5` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionVal1` mediumint(8) NOT NULL default '0',
  `RewFactionVal2` mediumint(8) NOT NULL default '0',
  `RewFactionVal3` mediumint(8) NOT NULL default '0',
  `RewFactionVal4` mediumint(8) NOT NULL default '0',
  `RewFactionVal5` mediumint(8) NOT NULL default '0',
  `RewFactionValOverride1` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride2` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride3` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride4` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride5` mediumint(8) unsigned NOT NULL default '0',
  `PointMapID` mediumint(8) unsigned NOT NULL default '0',
  `PointX` float NOT NULL default '0',
  `PointY` float NOT NULL default '0',
  `PointOption` mediumint(8) unsigned NOT NULL default '0',
  `Title` varchar(255) NOT NULL,
  `Objectives` varchar(255) NOT NULL,
  `Details` varchar(255) NOT NULL,
  `EndText` varchar(255) NOT NULL,
  `CompletionText` varchar(255) NOT NULL,
  `ReqCreatureOrGoID1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceID1` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIDMaxCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoID2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceID2` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIDMaxCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoID3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceID3` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIDMaxCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoID4` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceID4` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIDMaxCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID1` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID2` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID3` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID5` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount5` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemID6` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount6` mediumint(8) unsigned NOT NULL default '0',
  `CriteriaSpellID` mediumint(8) unsigned NOT NULL default '0',
  `ObjectiveText1` varchar(255) NOT NULL,
  `ObjectiveText2` varchar(255) NOT NULL,
  `ObjectiveText3` varchar(255) NOT NULL,
  `ObjectiveText4` varchar(255) NOT NULL,
  `RewCurrency1` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrencyCount1` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrency2` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrencyCount2` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrency3` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrencyCount3` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrency4` mediumint(8) unsigned NOT NULL default '0',
  `RewCurrencyCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrency1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrencyCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrency2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrencyCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrency3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrencyCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrency4` mediumint(8) unsigned NOT NULL default '0',
  `ReqCurrencyCount4` mediumint(8) unsigned NOT NULL default '0',
  `NPCFrameAcceptText1` varchar(255) NOT NULL,
  `NPCFrameAcceptText2` varchar(255) NOT NULL,
  `NPCFrameHandInText1` varchar(255) NOT NULL,
  `NPCFrameHandInText2` varchar(255) NOT NULL,
  `SoundID1` mediumint(8) unsigned NOT NULL default '0',
  `SoundID2` mediumint(8) unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
